export interface FaqData {
  q: string
  a: string[]
}

export const introduceData: string[] = [
  'SDCN is an infrastructure for sharing stable diffusion computing power.We are an open-source community born based on Stable Diffusion,We firmly believe in AI by the people for the people. The SDCN builds an AI image generation service platform that is accessible to everyone and offers a WYSIWYG experience. Developers use SDCN to write APIs for specific image processing effects that address a particular problem and generate targeted API interfaces for realistic photos, cartoon styles, futuristic cities, and other styles and formats. Users do not need to learn any skills or worry about where the computing power comes from. By using the Playground (calling various API interfaces contributed by developers), they can easily create the images they want.',
  'We would like to thank the computing power contributors. It is because of their presence that the world is full of freedom and light. We will be unregulated and unconstrained, allowing everyone to enjoy the beautiful life brought by AI computing power.',
]

export const faqData: FaqData[] = [
  {
    q: 'What is SDCN?',
    a: [
      'Stable Diffusion Computing Network (SDCN) is a distributed computing network based on Stable Diffusion. It is an open-source community project that brings together developers, computing power donors, and end-users to build a computing power community. SDCN provides a set of atomic operation APIs for Stable Diffusion, allowing developers to combine parameters for specific scenarios to generate new APIs and operation interfaces that are tailored for end-users. Computing power donors with GPU capabilities can join the SDCN network by contributing their computing power machines to the distributed computing power leaderboard. SDCN simplifies the complexity of text2image and image2image into personalized APIs, and allows individual computing power machines to join the SDCN network to gain more computing power resources. We believe in AI by the people for the people.',
    ],
  },
  {
    q: 'Where does SDCN get its computing power from?',
    a: [
      "SDCN's computing power resources come from donors who have idle GPU resources.",
    ],
  },
  {
    q: 'How can I become an SDCN donor?',
    a: [
      'There are no restrictions on donors, as long as you have idle computing power equipment, you can install the SDCN software and register on the SDCN website to join.',
    ],
  },
  {
    q: 'Who owns the copyright of the images generated by SDCN?',
    a: [
      'We do not own the copyright of the images produced by SDCN. It depends on the laws and regulations of the region or country you are in.',
    ],
  },
  {
    q: 'What is the development roadmap for SDCN?',
    a: [
      "SDCN will continue to improve the computing power, models, and APIs required for Stable Diffusion's text2image, image2image, and other capabilities. SDCN is a free AI service that is unregulated and not subject to centralized control. Everyone can donate their computing power machines, build basic or Lora models, write API service interfaces, and freely call SDCN to generate the content they need. You can explore the painting capabilities of AI through SDCN, add AI drawing functions to your web applications through SDCN, or use SDCN as a productivity efficiency tool. SDCN is just the beginning, and there will be more AI services running on the SDCN network in the future, allowing everyone to enjoy AI services freely.",
    ],
  },
  {
    q: 'Can SDCN be deployed on a private network?',
    a: [
      'SDCN is an open-source software that can be deployed independently on your own computing power equipment, forming a new SDCN network that belongs to you.',
    ],
  },
  {
    q: 'Who is SDCN for?',
    a: [
      'SDCN is for developers, computing power donors, and end-users who are interested in Stable Diffusion.',
    ],
  },
  {
    q: 'How does SDCN ensure stable computing power support?',
    a: [
      "SDCN's computing power initially came from friends' computers. As the community develops, more and more computing power donors appear, providing a stable computing power guarantee for SDCN.",
    ],
  },
  {
    q: 'What rewards do SDCN donors receive?',
    a: [
      'Currently, donors are motivated by their love for SDCN and the belief that it can change humanity. We believe in the spirit of "I for all, all for me". We believe that everyone has the right to use and enjoy AI freely, rather than allowing computing power to be controlled by a few companies or government organizations. In order to improve the network and create value for computing power donors and users, we may consider introducing an economic system to enable SDCN to self-develop in the future.',
    ],
  },
  {
    q: 'Is there a fee for using SDCN?',
    a: [
      'Currently, using SDCN is free. SDCN is an open-source community where you can donate computing power machines to the community and also buy coffee for developers.',
    ],
  },
  {
    q: 'What is the Honor System in SDCN?',
    a: [
      "The Honor System is SDCN's credit system that rewards users for correct behavior and helps prevent abuse of the system.",
    ],
  },
  {
    q: 'How can I obtain Honor in SDCN?',
    a: [
      'Users can obtain Honor in SDCN by registering as a website user, donating computing power nodes, or contributing to the community.',
    ],
  },
  {
    q: 'How does the Honor value of users affect the task execution queue?',
    a: [
      "The Honor value of different users only affects the sorting of their tasks in the execution queue. Whether the Honor value is high or low, everyone has the opportunity to use SDCN's computing power for calculations.",
    ],
  },
  {
    q: 'How are tasks sorted in the task queue?',
    a: [
      'Tasks are sorted in the task queue based on the Honor of the user who sends the task request, the wait time in the queue, and the computing power consumption required for the task.',
    ],
  },
  {
    q: 'Is there an anonymous API-key in SDCN?',
    a: [
      'Yes, there is a public anonymous API-key in SDCN, and its Honor value remains at 0.',
    ],
  },
]
